### PR TITLE
Eslint rules configuration correction

### PR DESCRIPTION
**Pull request by ghost**
## Story / Task

Closes https://github.com/bixlabs/documentation/issues/2

## Migrations

NO

## What this PR does?

Corrects the rules configuration of the `.eslintrc` file.

### Before 

Rules of eslint being ignored.

### After

Rules of eslint configured correctly.

### Related PRs
N/A

## How to test / reproduce
- Copy the eslint configuration on this PR
- Observe that the eslint configuration is being taken properly by eslint
- ???
- PROFIT

## TODOs
N/A

@jac1013

### CODE REVIEW

**Comment by acabreragnz** [comment]
`.eslintrc` without an extension [is deprecated](http://eslint.org/docs/user-guide/configuring), we should rename it to `.eslintrc.json`, 

What do you think @jac1013 @evasquez26?

**Comment by jac1013** [comment]
I agree @acabrera91

**Comment by ghost** [comment]
@acabrera91 sounds good to me

**Comment by ghost** [comment]
Done guys @acabrera91 @jac1013 :)

**Comment by jac1013** [comment]
Seems like we are good to merge this one, @acabrera91 do you agree?

**Comment by acabreragnz** [comment]
cool, ready to merge :)

**Pull request merged**
